### ISSUE TITLE
Overwrite original file

### ISSUE THREAD

**Issue by midzer** [pjox/gutf#1]
Hi,
great little tool :)

Right now, if input and output are the same resulting file is empty.
Is this intended or a bug?

Greets
midzer

**Comment by pjox** [comment]
Hello,

Thank you for the issue! This is actually intended behavior, gutf is specifically designed to convert huge files that don't fit into memory so input and output cannot have the same name and be in the same location. The input file cannot be overwritten as it is needed for the entirety of the conversion process (the whole file is never loaded into memory).

One thing you can do is have an output file with the same name as the input, but in a different location.

Hope this helps,
Pedro.

**Comment by midzer** [comment]
Thanks for your information. Putting output in another directory is a great workaround :)
I'll close this one for good.
